### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by itsbalvant** [OffchainLabs/orbit-actions#24]
i found critical vulnerability and i want to report it where to report and i checked bugbounty program in imunify but its out of scope this repo.

**Comment by leeederek** [comment]
Hey @itsbalvant! Thanks for letting our team know. We recommend that folks submit these sorts of reports to Immunefi regardless of whether you believe its out of scope or not. https://immunefi.com/bug-bounty/arbitrum/information/

Thanks!
